#!/bin/bash

SASFILE=$1

emacs \
    -l "~/projects/sass-mode/sass-output-mode.el" \
    -l "~/projects/sass-mode/sass-mode.el" \
    -batch $1 \
    --eval '(indent-region (point-min) (point-max))' \
    -f save-buffer
